### ISSUE TITLE
M5Unified化した後の互換性の維持について相談です。

### ISSUE THREAD

**Issue by mongonta0716** [meganetaaan/m5stack-avatar#72]
#69 にてM5Unified化とM5GFX化を行いましたが、旧仕様との互換性を確保していないことに気が付きました。
M5Stack.hやM5Core2.hをINCLUDEするとM5の二重定義のエラーでビルドできません。

自分の知識だと、ifdefで_M5STACK_H_や_M5CORE2_H_が定義されていた場合に以前のTFT_eSPIになるように分岐するという対応ぐらいしか思いつかないのですが @meganetaaan さんはどう思いますか？

**Comment by meganetaaan** [comment]
今後M5Stack＆Arduino環境では`M5Unified`を使うよう一本化されていくものと理解しています。なので基本的にアバター側で対応はせず、スケッチ側で`M5Stack.h`と`M5Core2.h`のインクルードを止めて`M5Unified.h`を使ってもらう対応でよいかと考えていました。

考えられるのはM5Unifiedに対応していない他のライブラリとアバターを組み合わせる場合ですが、具体的に困っている人がいなければ今のままにしたいと思います。いかがでしょうか？

**Comment by mongonta0716** [comment]
分かりました。

では特に対処はせずM5Unifiedの方を使ってもらうようにしていきましょう。
ありがとうございます。
